export const ADD_INCOME = "ADD_INCOME";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const BALANCE = "UPDATE_BALANCE";
export const ADD_INCOME_AMOUNT = "ADD_INCOME_AMOUNT";
export const ADD_INCOME_CATEGORY = "ADD_INCOME_CATEGORY";
export const ADD_INCOME_DATE = "ADD_INCOME_DATE";
export const ADD_INCOME_DESCRIPTION = "ADD_INCOME_DESCRIPTION";
